### ISSUE TITLE
Limit `[p]owner add/remove` to the main owner only.

### ISSUE THREAD

**Issue by Onii-Chan-Discord** [Noa-DiscordBot/Noa-Cogs#17]
### What cog is this feature request for?

ownermanagement

### Describe the feature request in as much detail as possible

I don't use this cog but right now, an owner can add another owner and that second owner is able to remove all other owners i can add a custom check if ya want.

**Comment by guacaplushy** [comment]
yea that does seem like a notable bug

**Comment by guacaplushy** [comment]
@Onii-Chan-Discord yeah you can make a custom check, do it in a pr

**Comment by Onii-Chan-Discord** [comment]
I won't be able to work on this so I'm closing this, sorry!

**Comment by JeffJrShim** [comment]
I'll work on this when I'm available.
