### ISSUE TITLE
[RandomNoa] v2 Update

### ISSUE THREAD

**Issue by JeffJrShim** [Noa-DiscordBot/noa-cogs#80]
## 🎉RandomNoa major version 2 is planned!
There will be No ETA on this, as we will be slowly working on it when we have time to do so. The issue will be locked to prevent any conversations and any unwanted discussions. A discussion is opened, please check #81 to chat about this update!

## 📝To-Do
- [x] Availability slot (#66)
- [ ] Improve embeds:
  - [x] fields, instead of description only
  - [ ] custom star emoji(?) (planned, search for emoji pls)
~~- [ ] add more easter eggs~~
- [x] new host #85

**Comment by reonanyubara** [comment]
**UPDATE!:**
A PR has been made (#83), please check it out for the RandomNoa v2 update.

**Comment by JeffJrShim** [comment]
> Add another,
> - change all image links to Discord (maybe?, suggestions please.)

We will be using @Glas host for this. (bae.lena.moe)

**Comment by JeffJrShim** [comment]
> Add another,
> - change all image links to Discord (maybe?, suggestions please.)

We will be using @DJTOMATO's host (bae.lena.moe)
